# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'motorsReactApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Required by RNFirebase
    pod 'Firebase/Core', '~> 6.8.1'

  # Pods for motorsReactApp
  pod 'Firebase/AdMob', '~> 6.8.1'
  pod 'Firebase/Analytics', '~> 6.8.1'
  pod 'Firebase/Database', '~> 6.8.1'
  pod 'Firebase/Messaging', '~> 6.8.1'


  pod 'toolbar-android', :path => '../node_modules/@react-native-community/toolbar-android'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'motorsReactAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
      installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
                config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
           end
      end
 end
